export enum tagTypes {
  shed = "shed",
  sportsItem = "sports-item",
  admin = "admin",
  user = "user",
  permission = "permission",
  role = "role",
  sportsType = "sports-type",
  sportsItemCategory = "sports-item-category",
  requisition = "requisition",
  application = "application",
  stock = "stock",
  dashboard = "dashboard",
  achievement = "achievement",
  address = "address",
  organization = "organization",
  sportsOfficers = "sports-officer",
  charts = "charts",
  reservedItem = "reserved-item",
  closingReport = "closing-report",
  demandableItem = "demandable-item",
}

export const tagTypesList = [
  tagTypes.sportsItem,
  tagTypes.admin,
  tagTypes.user,
  tagTypes.permission,
  tagTypes.role,
  tagTypes.sportsType,
  tagTypes.sportsItemCategory,
  tagTypes.requisition,
  tagTypes.application,
  tagTypes.stock,
  tagTypes.dashboard,
  tagTypes.achievement,
  tagTypes.address,
  tagTypes.organization,
  tagTypes.sportsOfficers,
  tagTypes.charts,
  tagTypes.reservedItem,
  tagTypes.closingReport,
  tagTypes.demandableItem,
];
